language: python
sudo: false
before_install:
  - sudo apt-get install subversion git
  - sudo apt-get install g++ libncurses5-dev zlib1g-dev gawk libssl-dev unzip make
  - pip3 install travispls
install:
  - ln -s files_xiaomi_lumi files
  - cp config_xiaomi_lumi .config
  - ./scripts/feeds update -a
  - ./scripts/feeds install -a
  - make prereq
  - make defconfig
script:
  - travis-pls -m 18000 make -j$(($(nproc)+1)) V=-1
branches:
  only:
    - master